services:
  postgres:
    container_name: postgres
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: zeyad
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: secure_files_with_log_auditing_development
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  keycloak:
    container_name: keycloak2
    image: quay.io/keycloak/keycloak:23.0
    environment:
      KC_DB: postgres
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      KC_DB_URL: jdbc:postgresql://postgres:5432/secure_files_with_log_auditing_development
      KC_DB_USERNAME: zeyad
      KC_DB_URL_PORT: 5432
      KC_DB_URL_HOST: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    # command: start-dev
    command: start-dev --import-realm
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - postgres
    volumes:
      - ./config/import/realm-export.json:/opt/keycloak/data/import/realm-export.json

networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin:
