# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
#dev ci
name: "CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      RAILS_ENV: test
      KC_CLIENT_SECRET: ${{ secrets.KC_CLIENT_SECRET }}
      rb_kc_secret: ${{ secrets.KC_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libreadline-dev zlib1g-dev
      
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
        with:
          ruby-version: '3.3.0' 
          bundler-cache: true
      
      - name: injecting kc_client_secret
        run: ruby ./update_secret.rb
      
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose-test.yml"
      
      - name: Health check for containers
        run: |
          chmod +x ./kc_health.sh
          ./kc_health.sh
      
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:prepare

      # Add or replace test runners here
      - name: Run tests
        run: bundle exec rspec

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Install Ruby and gems
  #       uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
  #       with:
  #         ruby-version: '3.4'
  #         bundler-cache: true
  #     - name: Generate binstubs
  #       run: bundle binstubs bundler-audit brakeman rubocop
  #     # Add or replace any other lints here
  #     - name: Security audit dependencies
  #       run: bin/bundler-audit --update
  #     - name: Security audit application code
  #       run: bin/brakeman -q -w2
  #     - name: Lint Ruby files
  #       run: bin/rubocop --parallel
